app_name            = "REPLACE_ME"
cost_center         = "REPLACE_ME"
owner_email         = "REPLACE_ME"
data_classification = "not_applicable"
database_name       = "REPLACE_ME"
kms_key_prefix      = "REPLACE_ME"
